create TABLE CONCERT
(
    ID   BINARY(16) PRIMARY KEY,
    TITLE      TINYTEXT NOT NULL,
    TYPE     TINYTEXT NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    LINK     TINYTEXT NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NOT NULL
)