CREATE TABLE CONCERT
(
    INFO_ID   BINARY(16) PRIMARY KEY,
    TITLE      TINYTEXT NOT NULL,
    GENRE     TINYTEXT NOT NULL,
    LOCATION  BINARY(16) NOT NULL,
    ARTIST    TEXT NOT NULL,
    PRE_TICKETING BINARY(16) NOT NULL,
    TICKETING BINARY(16) NOT NULL,
    CONCERT_DATE DATETIME NOT NULL,
    LINK     TINYTEXT NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NOT NULL
)