CREATE TABLE LOCATION
(
    LOCATION_ID   BINARY(16) PRIMARY KEY,
    COORDINATE_1    INT NOT NULL,
    COORDINATE_2    INT NOT NULL,
    COORDINATE_3    INT NOT NULL,
    LOCATION_NAME   VARCHAR(50) NOT NULL
)